# Config used to generate the preview pane.
# The preview is continuously rebuilt while you edit.

baseurl: /preview/  # Don't change this.
development: true

# Add your own config below, but don't forget to update
# _config_published.yaml too.
permalink: /blog/:categories/:year/:month/:day/:title.html
encoding: UTF-8